set(CMAKE_SYSTEM_NAME Emscripten)
set(EMSCRIPTEN ON)

set(EMSDK_PATH "$ENV{EMSDK}" CACHE PATH "Path to emsdk root")
if(NOT EMSDK_PATH)
    set(EMSDK_PATH "/home/blessdan/Programs/emsdk")
endif()

set(EMSCRIPTEN_ROOT "${EMSDK_PATH}/upstream/emscripten")

set(CMAKE_C_COMPILER   "${EMSCRIPTEN_ROOT}/emcc")
set(CMAKE_CXX_COMPILER "${EMSCRIPTEN_ROOT}/em++")
set(CMAKE_AR           "${EMSCRIPTEN_ROOT}/emar")
set(CMAKE_RANLIB       "${EMSCRIPTEN_ROOT}/emranlib")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXECUTABLE_SUFFIX ".js")
